#!/usr/bin/env node
/* Regenerates src/odoo/types.ts from the pinned spec with openapi-typescript.
 * The output is committed so bff/ and ai/ typecheck without running codegen, and so a
 * spec change shows up as a reviewable diff in the PR rather than only in CI logs.
 */
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const spec = join(here, '..', 'odoo', 'estimate-api.v1.json');
const out = join(here, '..', 'src', 'odoo', 'types.ts');
// Resolve the CLI through node's resolver so it works whether npm hoisted it to the root or not.
const require = createRequire(import.meta.url);
const bin = join(dirname(require.resolve('openapi-typescript/package.json')), 'bin', 'cli.js');

execFileSync(process.execPath, [bin, spec, '-o', out], { stdio: 'inherit' });

const header = '// GENERATED by openapi-typescript from odoo/estimate-api.v1.json. Do not edit by hand.\n'
  + '// Regenerate with: npm run gen -w contracts\n';
const body = await readFile(out, 'utf8');
await writeFile(out, header + body);
console.log(`wrote ${out}`);
