// GENERATED by openapi-typescript from odoo/estimate-api.v1.json. Do not edit by hand.
// Regenerate with: npm run gen -w contracts
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — no auth, no service hooks.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/estimate/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate Rates
         * @description The live rate card for the caller's role.
         */
        get: operations["estimate_rates_v1_estimate_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Estimate Rate Update
         * @description Write one edited Pricing Setup figure back into a pricelist card
         *     (staff only). The bound service re-resolves the source and writes
         *     as the caller's user, so native pricelist ACLs gate the write; a
         *     'derived' or unknown field is refused, never rounded.
         */
        patch: operations["estimate_rate_update_v1_estimate_rates_patch"];
        trace?: never;
    };
    "/v1/estimate/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate Rooms
         * @description The full live room pool, plus the free list when a check_in /
         *     check_out window is given. Same helpers as the compute response's
         *     roomNames / roomAvailability — one source, two transports.
         */
        get: operations["estimate_rooms_v1_estimate_rooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/estimate/boats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate Boats
         * @description The live dive-boat pool — the material planning resources with
         *     capacity > 1, name + cap per boat. Same helper as the rates
         *     response's boatNames — one source, two transports; boat costs
         *     never leave the staff role.
         */
        get: operations["estimate_boats_v1_estimate_boats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/estimate/pricelists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate Pricelists
         * @description The Scenario dropdown's card list — every product.pricelist,
         *     staff only. Same helper as the JSON-RPC /casa/estimate/pricelists
         *     route — one source, two transports.
         */
        get: operations["estimate_pricelists_v1_estimate_pricelists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/estimate/rates/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate Rate Manifest
         * @description The per-card rate manifest: seed assumptions + the field
         *     addressing the Pricing Setup tab writes back through (staff only).
         *     Same helper as the JSON-RPC /rate_manifest route.
         */
        get: operations["estimate_rate_manifest_v1_estimate_rates_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/estimate/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Estimate Compute
         * @description Price a scenario. Non-staff `assumptions` are IGNORED (a client
         *     cannot forge a rate); staff also receive costs and assumptions,
         *     agents/instructors a retail comparison model; guests get the same
         *     portal model minus the FOC block and the retail comparison.
         */
        post: operations["estimate_compute_v1_estimate_compute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/booking/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Booking Submit
         * @description Send the trip as a reservation request. The bound service sanitises
         *     the trip and creates a folio with draft quotations. Per-diver
         *     certificates ride on payload.attachments — validated by the existing
         *     pipeline, a bad file silently dropped, never fatal.
         */
        post: operations["booking_submit_v1_booking_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inquiry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inquiry List
         * @description List website inquiry leads by type/state (staff only). `state=new`
         *     also matches pre-existing leads whose state column is unset.
         */
        get: operations["inquiry_list_v1_inquiry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inquiry/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inquiry Detail
         * @description One inquiry lead in full (staff only). 404 when the id is unknown
         *     or is not an inquiry lead.
         */
        get: operations["inquiry_detail_v1_inquiry__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inquiry/{lead_id}/quoted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inquiry Quoted
         * @description Mark an inquiry lead handled (staff only). Idempotent — quoting a
         *     quoted lead is a no-op success. 404 when the id is unknown or not an
         *     inquiry lead.
         */
        post: operations["inquiry_quoted_v1_inquiry__lead_id__quoted_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/guest/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Guest Lookup
         * @description Look up a returning guest by phone (agent or staff). Single-match
         *     only: a number hitting two contacts returns matched=false unless a
         *     name narrows it to exactly one. Store the returned id and reuse it.
         */
        post: operations["guest_lookup_v1_guest_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Register
         * @description Open self-registration as guest/agent/instructor — the API twin of
         *     the website's /reserve/register onboarding. The bound service creates
         *     a portal user, writes the role on its partner, and (agent/instructor)
         *     stores the credential documents and files the front-desk verify
         *     To-Do; the account prices by its role immediately, `verified` stays
         *     False until the desk ticks that To-Do.
         */
        post: operations["auth_register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Login
         * @description Exchange an Odoo login/password for a native API key (scope
         *     'rpc') — the same credential the api-key header auth verifies, so a
         *     login here feeds every authenticated route. Credentials are checked
         *     by res.users.authenticate (native brute-force cooldown applies); the
         *     key TTL comes from the endpoint's `estimate_login_key_ttl_days`
         *     (0 = non-expiring).
         */
        post: operations["auth_login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Forgot Password
         * @description Start the native Odoo password-reset flow: if the address matches
         *     exactly one account, a time-limited reset link is EMAILED to it
         *     (auth_signup's /web/reset_password page) — the token never travels
         *     through this API. The response is identical whether or not the
         *     address is registered, so the route leaks no account existence.
         */
        post: operations["auth_forgot_password_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Logout
         * @description Log the caller out of Odoo by revoking the presented api-key —
         *     the native res.users.apikeys row is deleted (base revoke(): matched
         *     by the key's index, verified against the stored hash, ONLY that row
         *     — the user's other keys survive), so the key authenticates nothing
         *     from the next request on. There is no server-side session to end
         *     beyond the key: under http_basic/public no key travels, so the
         *     route answers ok with revoked=false and the client just discards
         *     its credentials.
         */
        post: operations["auth_logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Me
         * @description The authenticated caller's own profile — the identity behind the
         *     api-key. SECURED (keeps the padlock): unlike login, it is idempotent
         *     and mints no new key, so the app reuses the held key to rehydrate
         *     identity on resume and to refresh `verified` after the front desk
         *     approves — without re-logging in. Read-only: every field is edited in
         *     Odoo at the front desk, there is no profile-update route.
         */
        get: operations["auth_me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inquiry/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inquiry Submit
         * @description Create a classified crm.lead from the /location "Send an Inquiry"
         *     form and run its per-type follow-ups (rates sheet / booking-link
         *     note / verify To-Do / resort-inbox mail) — the API twin of the
         *     JSON-RPC /casa/booking/submit route, one source two transports. The
         *     Guest trip block is honoured only when inquiry_type is see_rates; a
         *     filled honeypot (`company_website`) is answered with ok=true and
         *     lead_id=null, on purpose.
         */
        post: operations["inquiry_submit_v1_inquiry_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttachmentInfo
         * @description One credential document filed on the partner — METADATA ONLY. The
         *     bytes never travel through the profile route; downloading a document
         *     is a separate, deliberate concern.
         */
        AttachmentInfo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Mimetype
             * @default
             */
            mimetype: string;
        };
        /**
         * BoatName
         * @description One live dive boat — id + name + capacity, never its cost
         *     (R-068; boat COSTS ride the staff-only assumptions).
         */
        BoatName: {
            /**
             * Id
             * @description Stable server handle (`db-<resource id>`) — the value to send as `guest.days[date].boatId`; the exact `name` is also accepted. Optional so a legacy name+cap payload still validates.
             */
            id?: string | null;
            /** Name */
            name: string;
            /** Cap */
            cap: number;
        };
        /**
         * BoatsResponse
         * @description The live dive-boat pool.
         *
         *     A read-only projection of the same helper the rates response rides
         *     (boatNames) — served so an external consumer can offer the dive
         *     planner's Boat dropdown without fetching a whole rate card.
         */
        BoatsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Boats
             * @description R-068's boat pool: material planning resources with capacity > 1, id + name + cap per boat, ordered by name. Send the id (or the exact name) as guest.days[date].boatId. Labels/caps only — boat costs never leave the staff role. Empty when the PMS capacity field is absent.
             */
            boats?: components["schemas"]["BoatName"][];
        };
        /** ComputeRequest */
        ComputeRequest: {
            trip: components["schemas"]["Trip"];
            /**
             * Assumptions
             * @description Staff-only rate overrides (deep-merged over defaults). IGNORED for any non-staff caller.
             */
            assumptions?: {
                [key: string]: unknown;
            } | null;
            /**
             * Today
             * @description Client date YYYY-MM-DD, trusted only within +/-2 days of server UTC (early-bird lead check); otherwise server UTC today.
             */
            today?: string | null;
        };
        /** ComputeResponse */
        ComputeResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Role */
            role: string;
            model: components["schemas"]["EstimateModel"];
            /** @description Present for staff and agent roles only. */
            retail_model?: components["schemas"]["EstimateModel"] | null;
            /**
             * Assumptions
             * @description The merged rate assumptions. Staff only.
             */
            assumptions?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CourseType
         * @enum {string}
         */
        CourseType: "dsd" | "refresher" | "ow" | "aow" | "rescue";
        /**
         * CustomItem
         * @description A free-form billed line the front desk resolves manually.
         */
        CustomItem: {
            /** Id */
            id?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Price
             * @default 0
             */
            price: number;
            /**
             * Qty
             * @default 1
             */
            qty: number;
            /** Mode */
            mode?: string | null;
            /** Date */
            date?: string | null;
            /** Dateto */
            dateTo?: string | null;
            /** Gids */
            gids?: string[];
        };
        /**
         * DayPlanEntry
         * @description One guest-day of the dive plan.
         */
        DayPlanEntry: {
            /**
             * Dive
             * @default false
             */
            dive: boolean;
            /**
             * Third
             * @default false
             */
            third: boolean;
            /**
             * Night
             * @default false
             */
            night: boolean;
            /** Boatid */
            boatId?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * EstimateModel
         * @description The priced model (engine compute_estimate output). All keys are
         *     Optional and extra keys are allowed so BOTH the full staff shape and
         *     the role-filtered portal shape validate against the one schema.
         */
        EstimateModel: {
            /** N */
            N?: number | null;
            /** Staydates */
            stayDates?: string[] | null;
            /** Divedates */
            diveDates?: string[] | null;
            /**
             * Quotes
             * @description One per-guest quote block per guest.
             */
            quotes?: {
                [key: string]: unknown;
            }[] | null;
            /** Catrev */
            catRev?: {
                [key: string]: unknown;
            } | null;
            /** Catgross */
            catGross?: {
                [key: string]: unknown;
            } | null;
            /** Catcost */
            catCost?: {
                [key: string]: unknown;
            } | null;
            /** Costs */
            costs?: {
                [key: string]: unknown;
            } | null;
            /** Cost */
            cost?: number | null;
            /** Extras */
            extras?: {
                [key: string]: unknown;
            } | null;
            /** Nondivers */
            nonDivers?: number | null;
            /** Divercount */
            diverCount?: number | null;
            /** Dayplans */
            dayPlans?: {
                [key: string]: unknown;
            }[] | null;
            /** Vans */
            vans?: number | null;
            /** Vanruns */
            vanRuns?: {
                [key: string]: unknown;
            }[] | null;
            kpis?: components["schemas"]["Kpis"] | null;
            /**
             * Warnings
             * @description Each {'level': 'warn'|'crit', 'text': str}. Includes input-provenance notes: omitted check-in/check-out (priced on sample dates, 'crit'), an omitted dive window (derived from the guests' marked dive days, 'warn'), and marked dive days outside the dive window ('crit' — they earn no dive revenue).
             */
            warnings?: {
                [key: string]: unknown;
            }[] | null;
            /** Gwin */
            gwin?: {
                [key: string]: unknown;
            } | null;
            /** Presence */
            presence?: {
                [key: string]: unknown;
            } | null;
            /**
             * Covers
             * @description Meal covers per date, keyed YYYY-MM-DD.
             */
            covers?: {
                [key: string]: unknown;
            } | null;
            /** Maxcovers */
            maxCovers?: number | null;
            /**
             * Gn
             * @description Total guest-nights.
             */
            gn?: number | null;
            /**
             * Roomnightsused
             * @description Nights used per Trip.rooms[].id.
             */
            roomNightsUsed?: {
                [key: string]: unknown;
            } | null;
            /**
             * Roompeak
             * @description Peak occupancy per Trip.rooms[].id.
             */
            roomPeak?: {
                [key: string]: unknown;
            } | null;
            foc?: components["schemas"]["FocInfo"] | null;
            /**
             * Roomnames
             * @description ALL live room resource names per room kind (e.g. {'standard': ['Standard A', ...]}), for the Room dropdown — the FULL pool, never pre-filtered by availability; clients fall back to 'Type #n' when absent.
             */
            roomNames?: {
                [key: string]: string[];
            } | null;
            /**
             * Roomavailability
             * @description FREE room resource names per room kind for the trip window — the native planning-conflict read. None when the trip dates are unknown; a kind absent from the dict has no availability data.
             */
            roomAvailability?: {
                [key: string]: string[];
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FieldRate
         * @description One patchable Pricing Setup figure, hard-locked to a product via
         *     its SKU (internal_reference) + the pricelist band min_quantity.
         *     `source` says which row backs it — a 'derived' figure
         *     (per-pax division or a percentage card) is read-only and a PATCH is
         *     refused.
         */
        FieldRate: {
            /**
             * Path
             * @description Assumptions path, e.g. roomRates.deluxe.3
             */
            path: string;
            /** Sku */
            sku?: string | null;
            /**
             * Category
             * @default
             */
            category: string;
            /** Min Qty */
            min_qty?: number | null;
            /** Price */
            price?: number | null;
            /**
             * Source
             * @description band | item | pricing | list_price | missing | derived.
             * @default
             */
            source: string;
            /** Product Tmpl Id */
            product_tmpl_id?: number | null;
            /** Row Id */
            row_id?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** FocActivity */
        FocActivity: {
            /** Heads */
            heads?: number | null;
            /** Entitled */
            entitled?: number | null;
            /** Marked */
            marked?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** FocInfo */
        FocInfo: {
            /** Ok */
            ok?: boolean | null;
            /** Per */
            per?: number | null;
            /** Bracket */
            bracket?: number | null;
            /** Entitled */
            entitled?: number | null;
            /** Marked */
            marked?: number | null;
            stay?: components["schemas"]["FocActivity"] | null;
            dive?: components["schemas"]["FocActivity"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FocRule
         * @description The server 5+1 FOC rule (R-056): `per` paying guests earn one free
         *     head (hotel_pms FOC_THRESHOLD - 1); `ok` mirrors the card's
         *     foc_5plus1_ok flag. The client seeds and locks its 'Guests per FOC'
         *     lever to this; the compute clamps it server-side regardless.
         */
        FocRule: {
            /**
             * Per
             * @default 5
             */
            per: number;
            /**
             * Ok
             * @default false
             */
            ok: boolean;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Email */
            email: string;
        };
        /** ForgotPasswordResponse */
        ForgotPasswordResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Message
             * @description Always the same message whether or not the address is registered — the reset link travels by email only.
             * @default
             */
            message: string;
        };
        /** Guest */
        Guest: {
            /** Id */
            id?: string | null;
            /**
             * Name
             * @default Guest
             */
            name: string;
            /**
             * Diver
             * @default true
             */
            diver: boolean;
            /**
             * Meals
             * @default true
             */
            meals: boolean;
            /**
             * Transport
             * @default true
             */
            transport: boolean;
            /**
             * Foc
             * @default false
             */
            foc: boolean;
            /**
             * Roomid
             * @description Links the guest to a Trip.rooms[].id.
             */
            roomId?: string | null;
            /** Courses */
            courses?: components["schemas"]["CourseType"][];
            /**
             * Days
             * @description Per-date dive plan, keyed YYYY-MM-DD.
             */
            days?: {
                [key: string]: components["schemas"]["DayPlanEntry"];
            };
            /** Arrive */
            arrive?: string | null;
            /** Depart */
            depart?: string | null;
            /** Comment */
            comment?: string | null;
            /** Vana */
            vanA?: string | null;
            /** Vand */
            vanD?: string | null;
            /** @description Per-guest transfer leg where a group splits across both legs (overrides the trip-level default for this guest). */
            transferDirection?: components["schemas"]["TransferDirection"] | null;
            /**
             * Diet
             * @description Free-form diet note; written to the guest's food_restriction (blank ones only) for the daily kitchen digest.
             * @default
             */
            diet: string;
            /**
             * Allergies
             * @description Free-form allergy note; joined with diet into the guest's food_restriction for the kitchen digest.
             * @default
             */
            allergies: string;
        };
        /**
         * GuestLookupRequest
         * @description Returning-guest lookup, phone-first. Phone travels in the BODY to
         *     keep numbers out of server request logs (agent or staff only).
         */
        GuestLookupRequest: {
            /** Phone */
            phone: string;
            /**
             * Name
             * @description Optional tiebreak: only narrows an already-multiple phone match, never widens the search.
             * @default
             */
            name: string;
        };
        /** GuestLookupResponse */
        GuestLookupResponse: {
            /**
             * Matched
             * @default false
             */
            matched: boolean;
            /** Id */
            id?: number | null;
            /** Name */
            name?: string | null;
        };
        /**
         * GuestType
         * @enum {string}
         */
        GuestType: "retail" | "agent" | "instructor";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * InquiryDetail
         * @description One inquiry lead in full (GET /v1/inquiry/{lead_id}), staff only.
         *     Carries the structured InquiryRequest fields the lead stores in typed
         *     columns, plus lead_id and created_at. The agent/instructor extras and
         *     total_guests/divers that the inquiry write side records in the lead's
         *     DESCRIPTION text (not typed columns) are returned verbatim in
         *     `description` — parse them from there, not from missing columns.
         */
        InquiryDetail: {
            /** Lead Id */
            lead_id: number;
            /**
             * Name
             * @default
             */
            name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Inquiry Type
             * @default
             */
            inquiry_type: string;
            /**
             * Casa Inquiry State
             * @default new
             */
            casa_inquiry_state: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Description
             * @description The lead's free-text description: special requests plus the agent/instructor extras and total_guests/divers stored there rather than in typed columns.
             * @default
             */
            description: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * InquiryListItem
         * @description One row of the staff inquiry list (GET /v1/inquiry).
         */
        InquiryListItem: {
            /** Lead Id */
            lead_id: number;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Casa Inquiry Type
             * @default
             */
            casa_inquiry_type: string;
            /**
             * Casa Inquiry State
             * @default new
             */
            casa_inquiry_state: string;
            /**
             * Created At
             * @description Lead create_date, ISO 8601, or empty.
             * @default
             */
            created_at: string;
        };
        /** InquiryListResponse */
        InquiryListResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Items */
            items?: components["schemas"]["InquiryListItem"][];
        };
        /** InquiryQuotedResponse */
        InquiryQuotedResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Lead Id */
            lead_id: number;
            /**
             * Casa Inquiry State
             * @default quoted
             */
            casa_inquiry_state: string;
        };
        /**
         * InquiryRequest
         * @description The /location "Send an Inquiry" form, SPA transport (one source
         *     with the JSON-RPC /casa/booking/submit route — both delegate to the
         *     website module's inquiry pipeline). Public route: the server
         *     re-validates every field on its own and silently drops a malformed
         *     entry — a bad answer never 500s and loses the enquiry (R-049).
         */
        InquiryRequest: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** @default see_rates */
            inquiry_type: components["schemas"]["InquiryType"];
            /**
             * Message
             * @description Special requests / free-text message.
             */
            message?: string | null;
            /**
             * Company Website
             * @description Honeypot — leave empty. A filled value is answered with a silent success and no lead.
             */
            company_website?: string | null;
            /** Nights */
            nights?: number | null;
            /**
             * Travel Month
             * @description Tentative month, "YYYY-MM".
             */
            travel_month?: string | null;
            same_stay_length?: components["schemas"]["YesNo"] | null;
            /** Total Guests */
            total_guests?: number | null;
            /** Rooms */
            rooms?: components["schemas"]["InquiryRoom"][];
            meal_plan?: components["schemas"]["MealPlan"] | null;
            airport_transfer?: components["schemas"]["YesNo"] | null;
            /** Divers */
            divers?: number | null;
            courses_interest?: components["schemas"]["YesNo"] | null;
            /** Contact Person */
            contact_person?: string | null;
            /** Agent Name */
            agent_name?: string | null;
            /** Agency */
            agency?: string | null;
            /** Agency Address */
            agency_address?: string | null;
            /** Diving Agency */
            diving_agency?: string | null;
            /** Country */
            country?: string | null;
            /**
             * Attachments
             * @description Credential documents (pdf/jpeg/png), agent & instructor only — the server stores at most two.
             */
            attachments?: components["schemas"]["RegisterAttachment"][];
        };
        /** InquiryResponse */
        InquiryResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Lead Id
             * @description The created lead, or null on a honeypot submission (silent success).
             */
            lead_id?: number | null;
        };
        /**
         * InquiryRoom
         * @description One row of the Guest inquiry rooms repeater — a wish, not
         *     inventory (stored as JSON text on the lead, D-5).
         */
        InquiryRoom: {
            /** @default standard */
            type: components["schemas"]["RoomType"];
            /** Pax */
            pax: number;
        };
        /**
         * InquiryType
         * @description The /location inquiry pill (crm.lead.casa_inquiry_type). Labels
         *     read Guest / Travel Agent / Dive Instructor; the VALUES are the
         *     historical ones on purpose so existing leads and filters keep
         *     working (D-4).
         * @enum {string}
         */
        InquiryType: "see_rates" | "agent" | "instructor";
        /**
         * Kpis
         * @description Portal roles receive revenue/rpgn/discounts/guests/nights only;
         *     cost, profit and margin are staff-only.
         */
        Kpis: {
            /** Revenue */
            revenue?: number | null;
            /** Cost */
            cost?: number | null;
            /** Profit */
            profit?: number | null;
            /** Margin */
            margin?: number | null;
            /** Rpgn */
            rpgn?: number | null;
            /** Discounts */
            discounts?: number | null;
            /** Guests */
            guests?: number | null;
            /** Nights */
            nights?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Login */
            login: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /**
             * Api Key
             * @description A native Odoo API key (scope 'rpc') — send it as the api-key header on every authenticated route. Shown ONCE; it is hashed at rest and cannot be re-read.
             */
            api_key: string;
            /** Role */
            role: string;
            /** Name */
            name: string;
            /** Login */
            login: string;
            /**
             * Expires At
             * @description Key expiry (UTC, ISO 8601), or null for a non-expiring key (endpoint TTL 0).
             */
            expires_at?: string | null;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Revoked
             * @description True when the presented api-key was revoked server-side (it authenticates nothing from now on). False when the request carried no api-key header — http_basic and public sessions hold no server-side token, so there is nothing to revoke and 'logging out' is purely client-side.
             */
            revoked: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * MeResponse
         * @description The authenticated caller's own profile — the identity behind the
         *     api-key. READ-ONLY: every field is edited by the front desk in Odoo,
         *     not through the API (there is no profile-update route). Fetch it any
         *     time with the held key: the app rehydrates identity on resume and
         *     refreshes `verified` after the desk approves, WITHOUT re-logging in
         *     (a re-login would mint a new key).
         */
        MeResponse: {
            /**
             * Id
             * @description Stable res.partner id (immutable).
             */
            id: number;
            /**
             * Role
             * @description staff / agent / instructor / guest / '' (guest).
             */
            role: string;
            /** Name */
            name: string;
            /** Login */
            login: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Verified
             * @description casa_website_role_verified — the front desk flips it to true after checking credentials. It is NOT is_agent (which drives commission); treat false as 'pending'. Guests are always false.
             * @default false
             */
            verified: boolean;
            /**
             * Contact Person
             * @description Agent contact person (agent/instructor only).
             */
            contact_person?: string | null;
            /** Agent Name */
            agent_name?: string | null;
            /** Agency */
            agency?: string | null;
            /** Agency Address */
            agency_address?: string | null;
            /**
             * Attachments
             * @description Credential documents filed on the partner during onboarding (agent/instructor) — metadata only.
             */
            attachments?: components["schemas"]["AttachmentInfo"][];
        };
        /**
         * MealPlan
         * @enum {string}
         */
        MealPlan: "full_board" | "room_only";
        /**
         * PricelistInfo
         * @description One product.pricelist row for the staff Scenario dropdown.
         */
        PricelistInfo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Currency
             * @default
             */
            currency: string;
            /**
             * Sequence
             * @default 0
             */
            sequence: number;
        };
        /**
         * PricelistsResponse
         * @description The Scenario dropdown's card list — every product.pricelist,
         *     staff-only. A non-staff caller is refused (403) before reaching this
         *     shape.
         */
        PricelistsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Pricelists */
            pricelists?: components["schemas"]["PricelistInfo"][];
            /**
             * Default Id
             * @description The walk-in Default card's id, or None.
             */
            default_id?: number | null;
        };
        /**
         * RateManifestResponse
         * @description The per-card rate manifest: the seed assumptions plus the field
         *     addressing the staff Pricing Setup tab writes back through (staff
         *     only).
         */
        RateManifestResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            pricelist?: components["schemas"]["PricelistInfo"] | null;
            /** Assumptions */
            assumptions?: {
                [key: string]: unknown;
            };
            /** Fields */
            fields?: components["schemas"]["FieldRate"][];
            foc?: components["schemas"]["FocRule"] | null;
        };
        /**
         * RateUpdateRequest
         * @description Write one edited Pricing Setup figure back into a pricelist card.
         *     The server re-resolves the (pricelist, sku, min_qty) source and
         *     refuses a 'derived' or unknown field; the figure is written
         *     verbatim, never rounded.
         */
        RateUpdateRequest: {
            /** Pricelist Id */
            pricelist_id: number;
            /** Sku */
            sku: string;
            /** Min Qty */
            min_qty?: number | null;
            /** Price */
            price: number;
        };
        /** RateUpdateResponse */
        RateUpdateResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Source
             * @default
             */
            source: string;
            /** Row Id */
            row_id?: number | null;
            /** Price */
            price?: number | null;
            /**
             * Path
             * @default
             */
            path: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * RatesResponse
         * @description The live rate card merged into the engine defaults. Every block is
         *     optional — the service returns what it can price and the engine falls
         *     back to its defaults for the rest.
         */
        RatesResponse: {
            /** Roomrates */
            roomRates?: {
                [key: string]: unknown;
            } | null;
            /** Divetiers */
            diveTiers?: {
                [key: string]: unknown;
            } | null;
            /** Mealrate */
            mealRate?: number | null;
            /** Courserates */
            courseRates?: {
                [key: string]: unknown;
            } | null;
            /** Transport */
            transport?: {
                [key: string]: unknown;
            } | null;
            /** Terms */
            terms?: {
                [key: string]: unknown;
            } | null;
            /**
             * Roomnames
             * @description ALL live room resource names per room kind, taken from the planning-role resources (front-desk renames tracked). The FULL pool — availability rides roomAvailability, never a filter on this list.
             */
            roomNames?: {
                [key: string]: string[];
            } | null;
            /**
             * Coursenames
             * @description Live course display names per course key (dsd / refresher / ow / aow / rescue), taken from the matching product's name. Labels only; prices ride courseRates.
             */
            courseNames?: {
                [key: string]: string;
            } | null;
            /**
             * Boatnames
             * @description The live dive-boat pool (R-068: material planning resources with capacity > 1), id + name + cap per boat, for the dive planner's Boat dropdown. The id is what guest.days[date].boatId takes. Labels/caps only — boat costs never leave the staff role.
             */
            boatNames?: components["schemas"]["BoatName"][] | null;
            /**
             * Discounts
             * @description Present (zeroed: agent=0, instructor=0) whenever the caller's role resolved a rate card — role cards are NET, the wholesale rate already carries the discount, so the percentage lever must not apply it a second time.
             */
            discounts?: {
                [key: string]: unknown;
            } | null;
            /**
             * Focok
             * @description Whether the caller's SERVER role earns the 5+1 FOC (the role card's foc_5plus1_ok). Absent for staff. The compute clamps promos.foc.on to this regardless of the payload.
             */
            focOk?: boolean | null;
            /**
             * Focper
             * @description The server 5+1 rule's paying-guests-per-free-head (hotel_pms FOC_THRESHOLD - 1). The compute clamps promos.foc.per to this for every caller.
             */
            focPer?: number | null;
            /**
             * Retailrates
             * @description Agent/instructor only: the GUEST card's own full rates payload. The engine prices the Agent View's retail comparison off this, so 'retail' means what a guest would actually pay, not the caller's own card.
             */
            retailRates?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RegisterAttachment
         * @description One credential document (agent/instructor onboarding). Validated
         *     server-side by the website's existing attachment pipeline (mimetype
         *     allowlist, magic bytes, 5MB cap) — a bad entry is silently dropped,
         *     exactly like the /reserve/register form.
         */
        RegisterAttachment: {
            /** Name */
            name: string;
            /** Mimetype */
            mimetype: string;
            /**
             * Data B64
             * @description Base64-encoded file body.
             */
            data_b64: string;
        };
        /**
         * RegisterRequest
         * @description Open self-registration, mirroring the website's /reserve/register
         *     onboarding: anyone registers as guest/agent/instructor; agent and
         *     instructor accounts stay unverified until the front desk ticks the
         *     verify To-Do their registration files.
         */
        RegisterRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * @description Becomes the login (lowercased).
             */
            email: string;
            /** Password */
            password: string;
            /** Phone */
            phone?: string | null;
            /** @description The onboarding role. agent/instructor file a front-desk verify To-Do; the role prices immediately, verification is a human step. */
            role: components["schemas"]["WebsiteRole"];
            /** Contact Person */
            contact_person?: string | null;
            /** Agent Name */
            agent_name?: string | null;
            /** Agency */
            agency?: string | null;
            /** Agency Address */
            agency_address?: string | null;
            /**
             * Attachments
             * @description Credential documents (pdf/jpeg/png), agent & instructor only — ignored for a guest.
             */
            attachments?: components["schemas"]["RegisterAttachment"][];
        };
        /** RegisterResponse */
        RegisterResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Login */
            login: string;
            /** Role */
            role: string;
            /**
             * Verified
             * @description Always False at registration — agent/instructor credentials are verified by the front desk.
             * @default false
             */
            verified: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** Room */
        Room: {
            /** Id */
            id?: string | null;
            /** @default standard */
            type: components["schemas"]["RoomType"];
            /**
             * Name
             * @description Bound physical room resource name, e.g. 'Deluxe B'. Optional: an unbound room keeps positional 'Type #n' labels. Shape-checked only — an unknown name prices identically and the front desk resolves it at reservation.
             */
            name?: string | null;
        };
        /**
         * RoomType
         * @enum {string}
         */
        RoomType: "standard" | "deluxe" | "suite";
        /**
         * RoomsResponse
         * @description The live room pool + trip-window availability.
         *
         *     A read-only projection of the same helpers the compute response
         *     rides — served so an external consumer can offer the Room dropdown
         *     without pricing a scenario.
         */
        RoomsResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Rooms
             * @description ALL live room resource names per room kind — the full physical pool. A kind with no planning resources is absent.
             */
            rooms?: {
                [key: string]: string[];
            };
            /**
             * Available
             * @description FREE room names per kind for the given window (native planning-conflict read). None when the window is missing, malformed or reversed.
             */
            available?: {
                [key: string]: string[];
            } | null;
            /**
             * Check In
             * @description Echo of the query.
             */
            check_in?: string | null;
            /**
             * Check Out
             * @description Echo of the query.
             */
            check_out?: string | null;
        };
        /**
         * SubmitAttachment
         * @description One per-diver certificate carried on the booking submit. Validated
         *     server-side by the website's existing attachment pipeline (mimetype
         *     allowlist, magic bytes, 5MB cap) — a bad or over-cap entry is silently
         *     dropped so a malformed upload can never break the booking. Files land
         *     on the folio, and where the guest_name matches a diver, also on their
         *     res.partner.
         */
        SubmitAttachment: {
            /** Guest Name */
            guest_name: string;
            /** Filename */
            filename: string;
            /** Mimetype */
            mimetype: string;
            /**
             * Data B64
             * @description Base64-encoded file body.
             */
            data_b64: string;
        } & {
            [key: string]: unknown;
        };
        /** SubmitContact */
        SubmitContact: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Phone */
            phone?: string | null;
        };
        /** SubmitRequest */
        SubmitRequest: {
            contact: components["schemas"]["SubmitContact"];
            trip: components["schemas"]["Trip"];
            /**
             * Attachments
             * @description Per-diver certificates. Over-cap or malformed entries are dropped, never fatal.
             */
            attachments?: components["schemas"]["SubmitAttachment"][];
        };
        /** SubmitResponse */
        SubmitResponse: {
            /** Success */
            success: boolean;
            /** Folio Id */
            folio_id?: number | null;
            /** Order Ids */
            order_ids?: number[] | null;
        };
        /**
         * TransferDirection
         * @description Which leg a transfer serves. Label/routing only — the price is the
         *     same either way; it rides through to the folio/van run so the desk
         *     knows which end to book.
         * @enum {string}
         */
        TransferDirection: "arrival" | "departure";
        /**
         * TransportType
         * @enum {string}
         */
        TransportType: "none" | "roundtrip" | "oneway";
        /**
         * Trip
         * @description The tool's trip, sanitised server-side by engine.sanitize_trip
         *     (unknown keys are dropped; exceeded caps raise -> HTTP 422).
         */
        Trip: {
            /** Label */
            label?: string | null;
            /** @default retail */
            guestType: components["schemas"]["GuestType"];
            /** @default none */
            transportType: components["schemas"]["TransportType"];
            /** @description Default transfer leg (arrival/departure) for the trip; a guest may override it per-guest where a group splits. */
            transferDirection?: components["schemas"]["TransferDirection"] | null;
            /** Checkin */
            checkIn?: string | null;
            /** Checkout */
            checkOut?: string | null;
            /**
             * Divefrom
             * @description Required (with diveTo) when any guest dives, unless the divers' own guest.days carry dive marks — then the window is derived from the marks.
             */
            diveFrom?: string | null;
            /**
             * Diveto
             * @description Required (with diveFrom) when any guest dives, unless the divers' own guest.days carry dive marks.
             */
            diveTo?: string | null;
            /**
             * Bookeddaysahead
             * @description Lead time in days for the early-bird check.
             * @default 0
             */
            bookedDaysAhead: number;
            /** Rooms */
            rooms?: components["schemas"]["Room"][];
            /** Guests */
            guests?: components["schemas"]["Guest"][];
            /** Items */
            items?: components["schemas"]["CustomItem"][];
            vanSplit?: components["schemas"]["VanSplit"] | null;
            /**
             * Vanmeta
             * @description Per-van-run overrides by run key.
             */
            vanMeta?: {
                [key: string]: components["schemas"]["VanMeta"];
            };
            /** Extradmbyday */
            extraDMByDay?: {
                [key: string]: string;
            };
            /** Dmbyday */
            dmByDay?: {
                [key: string]: string;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VanMeta */
        VanMeta: {
            /** Date */
            date?: string | null;
            /** Time */
            time?: string | null;
            /** Price */
            price?: number | null;
            /**
             * Foc
             * @default false
             */
            foc: boolean;
        };
        /**
         * VanSplit
         * @enum {string}
         */
        VanSplit: "equal" | "vehicle";
        /**
         * WebsiteRole
         * @description The onboarding role a self-registration carries (mirrors
         *     res.partner.casa_website_role — NOT GuestType, whose 'retail' is a
         *     pricing bucket, not an account role).
         * @enum {string}
         */
        WebsiteRole: "guest" | "agent" | "instructor";
        /**
         * YesNo
         * @enum {string}
         */
        YesNo: "yes" | "no";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_rates_v1_estimate_rates_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatesResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    estimate_rate_update_v1_estimate_rates_patch: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateUpdateResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is not staff (Pricing Setup is staff only), or the native pricelist ACLs refused the write. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No pricelist with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The field is unknown, derived (read-only) or carried a bad price. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    estimate_rooms_v1_estimate_rooms_get: {
        parameters: {
            query?: {
                check_in?: string | null;
                check_out?: string | null;
            };
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomsResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    estimate_boats_v1_estimate_boats_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoatsResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    estimate_pricelists_v1_estimate_pricelists_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricelistsResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is not staff (Pricing Setup is staff only), or the native pricelist ACLs refused the write. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    estimate_rate_manifest_v1_estimate_rates_manifest_get: {
        parameters: {
            query: {
                pricelist_id: number;
            };
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateManifestResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is not staff (Pricing Setup is staff only), or the native pricelist ACLs refused the write. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No pricelist with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    estimate_compute_v1_estimate_compute_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The scenario failed validation or breached an engine trust-boundary cap. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    booking_submit_v1_booking_submit_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inquiry_list_v1_inquiry_get: {
        parameters: {
            query?: {
                type?: string;
                state?: string;
            };
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryListResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is not staff (Pricing Setup is staff only), or the native pricelist ACLs refused the write. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inquiry_detail_v1_inquiry__lead_id__get: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryDetail"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is not staff (Pricing Setup is staff only), or the native pricelist ACLs refused the write. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No inquiry lead with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inquiry_quoted_v1_inquiry__lead_id__quoted_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryQuotedResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is not staff (Pricing Setup is staff only), or the native pricelist ACLs refused the write. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No inquiry lead with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    guest_lookup_v1_guest_lookup_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestLookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestLookupResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The caller is not staff (Pricing Setup is staff only), or the native pricelist ACLs refused the write. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auth_register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description The login (email) is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The payload failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No register service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auth_login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unknown login or wrong password (one message for both — no user enumeration). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_forgot_password_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auth_me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No estimate service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inquiry_submit_v1_inquiry_submit_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description The Accept-Language header is used to specify the language of the content to be returned. If a language is not available, the server will return the content in the default language. */
                "Accept-Language"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InquiryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InquiryResponse"];
                };
            };
            /** @description The payload failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited - the per-IP enquiry budget is shared with the website inquiry form. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No inquiry service is bound to this endpoint. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
