import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { extract } from "../src/extract.js";
import type { ExtractProvider } from "../src/provider.js";
import { checkEvidence, scoreCase, checkPricedFields, REQUIRED_FIELDS } from "../eval/score.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// The offline half of the eval. eval/runner.mjs asks a live provider the same 30
// dataset messages and prints a score; it costs tokens and needs a deployment, so it
// cannot be the gate that stops a date regression from shipping. This file replays the
// *answers a live run already gave* (eval/fixtures.mock-30.json, generated by
// eval/make-fixtures.mjs from eval/results.1789702974010.json — deepseek-flash through
// the local bff) through the real pipeline with no provider and no key, and compares the
// result against what that run produced (eval/baseline.deepseek-flash.json).
//
// What it can and cannot prove, said plainly:
//
//   * It proves the *pipeline's* rules — which dates are kept, which are refused, what
//     becomes a question, what code fills in — reproduce and improve on a real run.
//   * It does not measure model quality. The recorded answers carry the model's own
//     mistakes on purpose (vi-09's `guests: 8`, vi-07's `transport: true`), so a score
//     computed here is the score of *these* answers, not of the current model.
//
// That run's own report is eval/results-deepseek.log: required 63/87, fabricated 0,
// evidence verbatim 135/135, and `checkIn` mismatched on 19 of 30 cases because the
// phrase table could not read them (10月12日, 下周五, 15/10, thứ Bảy tới, Oct 10th …).

// manilaToday() when that run was recorded (2026-09-18T03:42:54Z). Held as RECORDED_TODAY
// in eval/make-fixtures.mjs too; the two have to agree or the baseline stops being
// comparable.
const RECORDED_TODAY = "2026-09-18";
// 00:00Z is 08:00 in Manila — the same calendar day, which is all manilaToday() reads.
const ANCHOR = new Date("2026-09-18T00:00:00Z");

beforeEach(() => {
  vi.useFakeTimers();
  vi.setSystemTime(ANCHOR);
});
afterEach(() => {
  vi.useRealTimers();
});

const readJson = async (name: string) => JSON.parse(await readFile(path.join(__dirname, "../eval", name), "utf8"));

const dataset = await readJson("dataset.mock-30.json");
const fixtures = await readJson("fixtures.mock-30.json");
const baseline = await readJson("baseline.deepseek-flash.json");

const fixtureById = new Map<string, { id: string; provenance: string; model: Record<string, unknown> }>(
  fixtures.cases.map((c: { id: string }) => [c.id, c]),
);
const baselineById = new Map<
  string,
  { id: string; trip: Record<string, { value: unknown; state: string; evidence: string | null }> }
>(baseline.cases.map((c: { id: string }) => [c.id, c]));


// The cases whose check-in the pre-fix pipeline deleted, marked by the generator rather than
// re-listed here. Two tags, and the difference between them is the whole story of the date
// work:
//
//   `:resolver`           the phrase table reads the quote itself, so the model's own date is
//                          never consulted. 17 of the 19.
//   `:resolver-language`  the same, for the two pairs with no year on them that used to be
//                          handed to the model: "05/12" (vi-09) and "12/10" (vi-10) are two
//                          valid calendar dates whichever way they are read, so the table
//                          refused them and corroboration had to judge the model's date. The
//                          guest's language — detected from that same message, the detection
//                          that fills trip.language — leaves exactly one reading now (dates.ts
//                          numericPairReadings). Both messages are Vietnamese, so both are
//                          day/month.
//
// `:model` is gone, and it is asserted gone rather than deleted, because it was the tag for the
// cases where the model's own date decided a money field — a model that read the pair
// backwards priced the wrong month. A tag with no cases behind it is the fix.
const recovered = fixtures.cases.filter((c: { provenance: string }) => c.provenance !== "recorded");
const idsWithTag = (tag: string) =>
  recovered.filter((c: { provenance: string }) => c.provenance.endsWith(":" + tag)).map((c: { id: string }) => c.id);
const modelDecided = idsWithTag("model");
const languageRead = idsWithTag("resolver-language");

/**
 * The date the guest's own words put the stay on — written from dataset.mock-30.json's
 * text, never from the fixture, so a wrong answer cannot be justified by the file it is
 * compared against. `addDays` counts from RECORDED_TODAY, a Friday (weekday phrases count
 * from there); `monthDay` is the guest's own day and month, with the year implied by "the
 * next time that day comes"; `noDate` is a message that genuinely has no date on it.
 *
 * Two entries disagree with the recorded run on purpose, because the run was wrong:
 * zh-08 (下周五 said on a Friday, which the old resolver pushed out to 2026-10-02) and
 * vi-07 (thứ Bảy tới, which it could not read at all).
 */
const GUEST_DATE: Record<
  string,
  { kind: "addDays"; value: number } | { kind: "monthDay"; value: string } | { kind: "noDate" }
> = {
  "en-01-complete": { kind: "addDays", value: 8 }, // next Saturday
  "en-02-missing-most": { kind: "addDays", value: 1 }, // this weekend
  "en-03-trap-unrelated-number": { kind: "addDays", value: 1 }, // arriving tomorrow
  "en-04-agent-multiple-rooms": { kind: "addDays", value: 7 }, // this Friday
  "en-05-relative-date-idiom": { kind: "addDays", value: 5 }, // in 5 days
  "en-06-padi-open-water": { kind: "monthDay", value: "10-10" }, // starting Oct 10th
  "en-07-fun-diving-package": { kind: "monthDay", value: "11-02" }, // starting Nov 2
  "en-08-family-non-divers": { kind: "monthDay", value: "12-01" }, // coming Dec 1st
  "en-09-trap-price-inquiry": { kind: "monthDay", value: "10-18" }, // 2 nights on Oct 18
  "en-10-solo-diver": { kind: "addDays", value: 7 }, // this Friday
  "vi-01-complete": { kind: "addDays", value: 1 }, // thứ Bảy này
  "vi-02-missing-dates": { kind: "noDate" }, // chưa chốt ngày, khoảng cuối tháng này
  "vi-03-trap-price-number": { kind: "addDays", value: 8 }, // cuối tuần sau
  "vi-04-khoa-hoc-lan-ow": { kind: "monthDay", value: "10-15" }, // từ ngày 15/10
  "vi-05-dai-ly-dat-doan": { kind: "monthDay", value: "11-20" }, // từ ngày 20/11
  "vi-06-gia-dinh-nghi-duong": { kind: "addDays", value: 7 }, // từ thứ Sáu tuần sau
  "vi-07-cuoi-tuan-lan-bien": { kind: "addDays", value: 1 }, // check in thứ Bảy tới
  "vi-08-hoi-gia-chung": { kind: "addDays", value: 1 }, // cuối tuần này
  "vi-09-bay-so-dien-thoai": { kind: "monthDay", value: "12-05" }, // từ ngày 05/12
  "vi-10-thue-xe-rieng": { kind: "monthDay", value: "10-12" }, // từ 12/10
  "zh-01-complete": { kind: "addDays", value: 8 }, // 下周六
  "zh-02-missing-most": { kind: "noDate" }, // 只问价格
  "zh-03-trap-phone-wechat": { kind: "monthDay", value: "10-12" }, // 10月12日
  "zh-04-padi-ow-course": { kind: "monthDay", value: "11-05" }, // 11月5号
  "zh-05-fun-dive-club": { kind: "monthDay", value: "10-20" }, // 10月20日
  "zh-06-agency-booking": { kind: "monthDay", value: "11-15" }, // 11月15日
  "zh-07-family-trip": { kind: "monthDay", value: "12-10" }, // 12月10日
  "zh-08-relative-date": { kind: "addDays", value: 7 }, // 下周五, said on a Friday
  "zh-09-room-only": { kind: "monthDay", value: "10-24" }, // 10月24日
  "zh-10-trap-price-inquiry": { kind: "monthDay", value: "11-08" }, // 11月8日
};

// The one case where the recorded model said nothing about the date at all (the log
// scores it required 0/3), so its fixture has no evidence to reuse when a test injects a
// correct date. "on Oct 18" is quoted from the guest's own message.
const DATE_EVIDENCE: Record<string, string> = { "en-09-trap-price-inquiry": "on Oct 18" };

function addDays(iso: string, days: number): string {
  const d = new Date(`${iso}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

/** The ISO the guest's own phrase means, per GUEST_DATE. */
function guestIso(id: string): string | null {
  const expected = GUEST_DATE[id];
  if (!expected || expected.kind === "noDate") return null;
  return expected.kind === "addDays"
    ? addDays(RECORDED_TODAY, expected.value)
    : `${RECORDED_TODAY.slice(0, 4)}-${expected.value}`;
}

type Field = { value: unknown; state: string; evidence: string | null };
type Trip = Record<string, Field>;
type Model = Record<string, Field>;

function providerReturning(raw: unknown): ExtractProvider {
  return {
    id: "replay:stub",
    call: vi.fn().mockResolvedValue({ raw, tokensIn: 0, tokensOut: 0, cacheReadTokens: 0, ms: 1 }),
  };
}

/**
 * Every dataset message through extract() with its recorded answer — optionally rewritten
 * by `edit`, which is how the three model behaviours below are produced. `calls` counts
 * provider invocations: more than one per case means a retry, i.e. that a fixture answer
 * failed schema validation and the model would have been asked again.
 */
async function replay(edit: (id: string, model: Model) => void = () => {}) {
  const trips = new Map<string, Trip>();
  const questions = new Map<string, string[]>();
  let calls = 0;
  for (const item of dataset as Array<{ id: string; text: string }>) {
    const fixture = fixtureById.get(item.id)!;
    const model = structuredClone(fixture.model) as Model;
    edit(item.id, model);
    const provider = providerReturning(model);
    try {
      const outcome = await extract(item.text, provider);
      trips.set(item.id, outcome.trip as unknown as Trip);
      questions.set(item.id, outcome.questions.map((q) => String(q.field)));
    } catch (err) {
      throw new Error(`${item.id}: the recorded answer no longer extracts — ${(err as Error).message}`);
    }
    calls += vi.mocked(provider.call).mock.calls.length;
  }
  return { trips, questions, calls };
}

/** Injects the date the guest actually wrote, as a model that read the message properly. */
function withCorrectDates(id: string, model: Model): void {
  const expected = GUEST_DATE[id];
  if (!expected || expected.kind === "noDate") return;
  const evidence = model.checkIn?.evidence ?? DATE_EVIDENCE[id];
  if (!evidence) throw new Error(`${id} has a date in the guest's words but no evidence phrase to quote`);
  model.checkIn = { value: guestIso(id), state: "stated", evidence };
}

/** The same date, a week late — the error a model makes when it mis-reads a week or a month. */
function withWeekLateDates(id: string, model: Model): void {
  withCorrectDates(id, model);
  if (typeof model.checkIn?.value === "string") model.checkIn = { ...model.checkIn, value: addDays(model.checkIn.value, 7) };
}

/** A model date with nothing in the guest's words to hold it to, which must be refused. */
function withSpeculativeDate(id: string, model: Model): void {
  if (id !== "vi-02-missing-dates") return;
  model.checkIn = { value: "2026-09-30", state: "stated", evidence: "cuối tháng này" };
}

const DIVE_FIELDS = ["diver", "diveFrom", "diveTo"];

describe("eval replay — the recorded deepseek-flash run, re-run offline", () => {
  it("replays all 30 cases through the pipeline, with no provider and no retry", async () => {
    const { trips, calls } = await replay();
    expect(trips.size).toBe(dataset.length);
    // One call per case: every recorded answer still passes schema validation, so none of
    // them would have cost the model a second round-trip.
    expect(calls).toBe(dataset.length);
    for (const item of dataset) {
      const trip = trips.get(item.id)!;
      for (const key of Object.keys(baselineById.get(item.id)!.trip)) {
        expect(trip[key], `${item.id}.${key} came back with no state at all`).toBeDefined();
      }
    }
  });

  it("reproduces that run field for field, apart from the check-in dates this work recovers", async () => {
    const { trips } = await replay();
    // Fields where the fixture and the recording are *meant* to differ. The dive rules
    // tightened after that run (below), and the two fields below those belong to code: the
    // recording has the model answering `transportType` itself — quoting the guest's words
    // as its "evidence", the one thing the model is not trusted with — and the fixture
    // deliberately leaves it out so postProcess derives it from `transport` again. The
    // value still has to match; only the state and the invented evidence differ.
    // `guests` is here for the same kind of reason: the recording has vi-09's `guests: 8`
    // for a message that says both 8 and 4, and corroborateCount (counts.ts) turns a count
    // the guest's own words contradict into a question instead of a price. The fixture
    // still carries the model's 8 — the answer is replayed wrong on purpose — so this is
    // the field where the current pipeline is meant to differ from that run.
    const intended = new Set([...DIVE_FIELDS, "checkIn", "checkOut", "transportType", "guests"]);
    const changedDates: string[] = [];

    for (const item of dataset) {
      const before = baselineById.get(item.id)!.trip;
      const after = trips.get(item.id)!;

      // The nine fields this work does not touch must be exactly what that run produced.
      for (const [field, previous] of Object.entries(before)) {
        if (intended.has(field)) continue;
        expect(after[field], `${item.id}.${field} changed since that run`).toEqual(previous);
      }

      // transportType follows the guest's transport answer, whatever the model offered:
      // en-06's recording has it as `oneway` for a message that only says "need van from
      // NAIA airport" — a guess, not a quote, and one the guest would be priced for.
      const derivedFromTransport = after.transport.value === true ? "roundtrip" : "none";
      expect(after.transportType.value, `${item.id}.transportType must follow the transport answer`).toBe(
        derivedFromTransport,
      );
      expect(["derived", "default"]).toContain(after.transportType.state);
      expect(after.transportType.evidence).toBeNull();

      // A date that run had already resolved must resolve to the same day — this is the
      // guard on the phrase table: adding entries must not move a date that was right.
      if (before.checkIn.state === "stated") {
        expect(after.checkIn, `${item.id}.checkIn was already right and moved`).toEqual(before.checkIn);
      }

      // A date it deleted is either back (and marked as such in the fixture) or still
      // missing because no model ever offered one (en-09: the run returned nothing at all
      // for that message, which is a model problem, not a date-parsing one).
      if (before.checkIn.state === "missing" && after.checkIn.state === "stated") {
        changedDates.push(item.id);
        expect(
          recovered.map((c: { id: string }) => c.id),
          `${item.id} gained a date on its own — the fixture never proposed one`,
        ).toContain(item.id);
      }

      // check-out is arithmetic on the guest's own answers, never the model's date.
      if (after.checkIn.state === "stated" && typeof after.nights.value === "number") {
        expect(after.checkOut.value).toBe(addDays(after.checkIn.value as string, after.nights.value as number));
      } else {
        expect(after.checkOut.state, `${item.id}.checkOut outlived its check-in`).toBe("missing");
      }
      expect(after.checkOut.state === "derived" || after.checkOut.state === "missing").toBe(true);
    }

    expect(changedDates.sort()).toEqual(recovered.map((c: { id: string }) => c.id).sort());
  });

  it("keeps a dive window only as a date inside the stay, and asks about every other one", async () => {
    const { trips } = await replay();
    const windowsKept: string[] = [];

    for (const item of dataset) {
      const before = baselineById.get(item.id)!.trip;
      const after = trips.get(item.id)!;
      const stayFrom = after.checkIn.state === "stated" ? (after.checkIn.value as string) : null;
      const stayTo = after.checkOut.state === "derived" ? (after.checkOut.value as string) : null;

      for (const field of DIVE_FIELDS) {
        // ADR-006 Decision 4: dive revenue is priced from `diver` and the window, so
        // anything the run inferred — and anything code cannot settle as a date the stay
        // contains — has to be a question. `diver` is the field that gates the other two.
        if (after[field].state !== "stated") {
          expect(after[field].state, `${item.id}.${field} is a money field and must be asked about`).toBe("missing");
          expect(before[field].state, `${item.id}.${field} was missing in that run too`).not.toBe("stated");
          continue;
        }
        if (field === "diver") {
          expect(after[field], `${item.id}.diver`).toEqual(before[field]);
          continue;
        }
        windowsKept.push(`${item.id}.${field}`);
        expect(after[field].value, `${item.id}.${field} is stated as something that is not a date`).toMatch(
          /^\d{4}-\d{2}-\d{2}$/,
        );
        if (stayFrom) expect((after[field].value as string) >= stayFrom, `${item.id}.${field} starts before the stay`).toBe(true);
        if (stayTo) expect((after[field].value as string) <= stayTo, `${item.id}.${field} ends after the stay`).toBe(true);
      }
    }

    // The one window that run stated was vi-04's `diveFrom: "15/10"` — the guest's own
    // phrase, handed back where a date belongs. Code resolves it (dates.ts) instead of
    // asking the guest for the date they already wrote, and the stay that came out of the
    // same message (check-in 15/10, four nights) contains it.
    expect(windowsKept).toEqual(["vi-04-khoa-hoc-lan-ow.diveFrom"]);
    expect(trips.get("vi-04-khoa-hoc-lan-ow")!.diveFrom.value).toBe("2026-10-15");
  });

  it("turns the count the guest's own words contradict into a question (vi-09)", async () => {
    const { trips, questions } = await replay();
    const trip = trips.get("vi-09-bay-so-dien-thoai")!;

    // "nhóm mình có 8 người nhưng chỉ 4 người ở lại 2 đêm": the recorded answer took the 8,
    // and its evidence was the guest's own words — a verbatim substring, so evidence
    // enforcement had nothing to object to — and the estimate would have been priced for a
    // group twice the size of the one actually staying. counts.ts asks instead of choosing.
    expect(trip.guests.state).toBe("missing");
    expect(trip.guests.value).toBeNull();
    expect(trip.guests.evidence).toBeNull();
    expect(questions.get("vi-09-bay-so-dien-thoai")).toContain("guests");

    // The rest of that sentence survives: one number for the nights, and the check-in the
    // recording never stored comes back as the day the guest wrote.
    expect(trip.nights.value).toBe(2);
    expect(trip.nights.state).toBe("stated");
    expect(trip.checkIn.value).toBe("2026-12-05");
  });

  it("never keeps a required field with a value the guest did not give — it asks instead", async () => {
    const { trips, questions } = await replay();
    const keptWrong: string[] = [];
    const asked: string[] = [];
    let stated = 0;

    for (const item of dataset) {
      const trip = trips.get(item.id)!;
      const askedHere = questions.get(item.id) ?? [];
      for (const field of REQUIRED_FIELDS) {
        if (item.expected[field]?.state !== "stated") continue;
        stated += 1;
        const actual = trip[field];
        if (actual.state === "stated") {
          // Stated means the guest gave it. A value that is not the one the dataset's own
          // text contains is the money bug this work is about: it is priced as an answer.
          if (item.expected[field].value !== undefined && actual.value !== item.expected[field].value) {
            keptWrong.push(`${item.id}.${field}=${String(actual.value)}`);
          }
          continue;
        }
        // Not stated: the guest's answer is not in the trip, so it has to be asked for.
        asked.push(`${item.id}.${field}`);
        expect(askedHere, `${item.id}.${field} is neither kept nor asked about`).toContain(field);
      }
    }

    // The invariant, and the acceptance check for this work: of the required fields the
    // corpus says the guest stated, none is kept with a value the guest did not give.
    // vi-09's `guests: 8` used to be exactly that — priced, and never asked about.
    expect(stated).toBe(87);
    expect(keptWrong).toEqual([]);
    // Five of the 87 are not kept, and each is a question rather than a silence (asserted
    // above). Four are answers the recorded model never supplied — en-09's whole message
    // scored 0/3 in that run's own log, and en-10 says "Solo diver" without the model
    // recording a count — and the fifth is vi-09's `guests`, the count the guest's own words
    // contradict. Pinned so a new gap shows up as a failure here rather than as a field that
    // quietly stopped being asked about.
    expect(asked).toEqual([
      "en-09-trap-price-inquiry.checkIn",
      "en-09-trap-price-inquiry.guests",
      "en-09-trap-price-inquiry.nights",
      "en-10-solo-diver.guests",
      "vi-09-bay-so-dien-thoai.guests",
    ]);
  });

  it("recovers every deleted date as the day the guest actually wrote", async () => {
    const { trips } = await replay();
    expect(recovered).toHaveLength(19);

    for (const [id, trip] of trips) {
      const expected = GUEST_DATE[id];
      expect(expected, `${id} has no entry in GUEST_DATE`).toBeDefined();
      if (trip.checkIn.state !== "stated") {
        expect(trip.checkIn.value, `${id} kept a value while not being stated`).toBeNull();
        continue;
      }
      expect(expected.kind, `${id} ended up with a date, but the message has none`).not.toBe("noDate");
      if (expected.kind === "monthDay") {
        expect(String(trip.checkIn.value)).toMatch(new RegExp(`-${expected.value}$`));
      } else {
        expect(trip.checkIn.value).toBe(addDays(RECORDED_TODAY, expected.value));
      }
      expect(trip.checkIn.evidence, `${id} has a date but no quote from the guest`).not.toBeNull();
    }
  });

  it("scores the same as that run's own report, plus the 19 fields it lost", async () => {
    const { trips } = await replay();

    const aggregate = (tripOf: (id: string) => Trip) => {
      let fabricated = 0;
      let requiredTotal = 0;
      let requiredCorrect = 0;
      let stated = 0;
      let evidenceOk = 0;
      for (const item of dataset as Array<{ id: string; text: string }>) {
        const trip = tripOf(item.id);
        const scored = scoreCase(item, trip);
        fabricated += scored.fabricated;
        requiredTotal += scored.requiredTotal;
        requiredCorrect += scored.requiredCorrect;
        const ev = checkEvidence(trip, item.text);
        stated += ev.stated;
        evidenceOk += ev.evidenceOk;
      }
      return { fabricated, requiredTotal, requiredCorrect, stated, evidenceOk };
    };

    const before = aggregate((id) => baselineById.get(id)!.trip);
    const after = aggregate((id) => trips.get(id)!);

    // The recording's own report, re-derived from the baseline file by the live runner's
    // scoring code (results-deepseek.log: "Required fields correct: 63/87").
    expect(before.requiredTotal).toBe(87);
    expect(before.requiredCorrect).toBe(63);

    expect(after.fabricated, "a field was invented for a message that never stated it").toBe(0);
    expect(after.evidenceOk).toBe(after.stated); // verbatim, checked in code, 100%
    expect(after.stated).toBeGreaterThan(before.stated);

    // Exactly the 19 date fields, and nothing else, changed hands. The live run's ≥95%
    // threshold is not reachable with *these* answers — vi-09's `guests: 8` and en-09's
    // three missing fields are the model's errors, preserved in the fixture on purpose.
    expect(after.requiredTotal).toBe(before.requiredTotal);
    expect(after.requiredCorrect).toBe(before.requiredCorrect + recovered.length);
  });
});

describe("eval replay — what the pipeline does with the date a model offers", () => {
  it("keeps every date the guest wrote, and asks only about the messages that have none", async () => {
    const { trips, questions } = await replay(withCorrectDates);

    for (const [id, trip] of trips) {
      const expected = GUEST_DATE[id];
      if (expected.kind === "noDate") {
        expect(trip.checkIn.state, `${id} has no date in it and must still be asked about`).toBe("missing");
        expect(questions.get(id)).toContain("checkIn");
        continue;
      }
      expect(trip.checkIn.state, `${id} states a date and must not be re-asked for it`).toBe("stated");
      expect(trip.checkIn.value).toBe(guestIso(id));
      expect(trip.checkIn.evidence).not.toBeNull();
      expect(questions.get(id), `${id} has its date, so it must not be asked again`).not.toContain("checkIn");
    }
  });

  it("refuses a week-late date, and never records one as stated", async () => {
    const { trips, questions } = await replay(withWeekLateDates);

    for (const [id, trip] of trips) {
      if (trip.checkIn.state !== "stated") continue;
      // Whatever the model said, a stated date is the guest's own day: either the
      // resolver read the phrase itself, or corroboration checked it against the words.
      expect(trip.checkIn.value, `${id} recorded a date the guest did not write`).toBe(guestIso(id));
    }

    // Nothing is left to the model any more. The two cases that were are the ambiguous day/month
    // pairs "05/12" (vi-09) and "12/10" (vi-10): code reads both from the guest's own language
    // now, so a week-late model date neither moves them nor gets them deleted — the guest keeps
    // the day they wrote instead of being asked for it again, which is the point of reading the
    // pair rather than asking about it.
    expect(modelDecided).toEqual([]);
    expect(languageRead).toEqual(["vi-09-bay-so-dien-thoai", "vi-10-thue-xe-rieng"]);
    for (const id of languageRead) {
      expect(trips.get(id)!.checkIn.value, `${id} lost the day its own guest wrote`).toBe(guestIso(id));
      expect(questions.get(id)).not.toContain("checkIn");
    }
  });

  it("refuses a date the guest's own words do not support", async () => {
    const { trips, questions } = await replay(withSpeculativeDate);
    const trip = trips.get("vi-02-missing-dates")!;
    // "chưa chốt ngày, khoảng cuối tháng này" — a month, not a day. A model offering the
    // 30th is guessing, and a guessed check-in is a wrong price (dates.ts, vi-02).
    expect(trip.checkIn.state).toBe("missing");
    expect(trip.checkIn.value).toBeNull();
    expect(trip.checkIn.evidence).toBeNull();
    expect(questions.get("vi-02-missing-dates")).toContain("checkIn");
  });
});

describe("eval replay — the priced fields the score used to ignore", () => {
  it("scores transport the way the live runner does, and pins the recorded mistake", async () => {
    const { trips } = await replay();
    const mismatched: string[] = [];
    let checked = 0;

    for (const item of dataset) {
      const priced = checkPricedFields(item, trips.get(item.id)!);
      checked += priced.checked;
      for (const m of priced.mismatches) mismatched.push(`${item.id}.${m.field}`);
    }

    // 20 of the 30 messages say something about the airport transfer, one way or the other.
    expect(checked).toBe(20);

    // Two recorded answers make this mistake, in two languages, and both are the same one:
    // a guest who says they are driving themselves comes back as `transport: true`, with
    // their own sentence ("xe tụi mình tự đi", "自己开车过去") as the evidence — so evidence
    // enforcement could not see it, and nothing scored it. vi-07 is Vietnamese, zh-09
    // Chinese: that the model does it twice says it is a prompt/schema problem rather than
    // a one-off, which is exactly what this assertion is for. The answers are replayed
    // wrong on purpose (make-fixtures.mjs); what the assertion buys is that the mistake is
    // *visible* in the score, and that a third one cannot appear without failing here.
    expect(mismatched).toEqual(["vi-07-cuoi-tuan-lan-bien.transport", "zh-09-room-only.transport"]);
  });
});

describe("eval fixtures", () => {
  it("say where they came from, and which cases were restored by hand", async () => {
    expect(fixtures.provenance.recordedToday).toBe(RECORDED_TODAY);
    expect(baseline.provenance.recordedToday).toBe(RECORDED_TODAY);
    expect(fixtures.provenance.recording).toBe(baseline.provenance.recording);
    expect(fixtures.provenance.provider).toContain("deepseek");
    expect(fixtures.provenance.generatedBy).toBe("eval/make-fixtures.mjs");

    const ids = (list: Array<{ id: string }>) => new Set(list.map((c) => c.id));
    expect(ids(fixtures.cases)).toEqual(ids(dataset));
    expect(ids(baseline.cases)).toEqual(ids(dataset));

    // The 19 the pre-fix pipeline deleted, marked by provenance so the suite can tell a
    // recovered date from one that was there all along.
    const authored = fixtures.cases.filter((c: { provenance: string }) => c.provenance !== "recorded");
    expect(authored).toHaveLength(19);
    for (const c of authored) expect(c.provenance.startsWith("authored-checkIn:")).toBe(true);
    // No check-in is decided by the model's own date any more: the two that were are the
    // ambiguous pairs the guest's detected language settles (see the week-late test above).
    expect(modelDecided).toEqual([]);
    expect(languageRead).toHaveLength(2);

    // GUEST_DATE is this file's only independent expectation about dates: a message added
    // to the dataset without one would otherwise be scored as "no opinion" and pass.
    for (const item of dataset as Array<{ id: string }>) {
      expect(GUEST_DATE[item.id], `${item.id} is missing from GUEST_DATE`).toBeDefined();
    }
  });
});



