import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { extract } from "../src/extract.js";
import type { ExtractProvider } from "../src/provider.js";
import { checkEvidence, scoreCase, checkPricedFields, REQUIRED_FIELDS } from "../eval/score.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// The offline half of the eval. eval/runner.mjs asks a live provider the same 30
// dataset messages and prints a score; it costs tokens and needs a deployment, so it
// cannot be the gate that stops a date regression from shipping. This file replays the
// *answers a live run already gave* (eval/fixtures.mock-30.json, generated by
// eval/make-fixtures.mjs from eval/results.1789702974010.json — deepseek-flash through
// the local bff) through the real pipeline with no provider and no key, and compares the
// result against what that run produced (eval/baseline.deepseek-flash.json).
//
// What it can and cannot prove, said plainly:
//
//   * It proves the *pipeline's* rules — which dates are kept, which are refused, what
//     becomes a question, what code fills in — reproduce and improve on a real run.
//   * It does not measure model quality. The recorded answers carry the model's own
//     mistakes on purpose (vi-09's `guests: 8`, vi-07's `transport: true`), so a score
//     computed here is the score of *these* answers, not of the current model.
//
// That run's own report is eval/results-deepseek.log: required 63/87, fabricated 0,
// evidence verbatim 135/135, and `checkIn` mismatched on 19 of 30 cases because the
// phrase table could not read them (10月12日, 下周五, 15/10, thứ Bảy tới, Oct 10th …).

// manilaToday() when that run was recorded (2026-09-18T03:42:54Z). Held as RECORDED_TODAY
// in eval/make-fixtures.mjs too; the two have to agree or the baseline stops being
// comparable.
const RECORDED_TODAY = "2026-09-18";
// 00:00Z is 08:00 in Manila — the same calendar day, which is all manilaToday() reads.
const ANCHOR = new Date("2026-09-18T00:00:00Z");

beforeEach(() => {
  vi.useFakeTimers();
  vi.setSystemTime(ANCHOR);
});
afterEach(() => {
  vi.useRealTimers();
});

const readJson = async (name: string) => JSON.parse(await readFile(path.join(__dirname, "../eval", name), "utf8"));

const dataset = await readJson("dataset.mock-30.json");
const fixtures = await readJson("fixtures.mock-30.json");
const baseline = await readJson("baseline.deepseek-flash.json");

const fixtureById = new Map<string, { id: string; provenance: string; model: Record<string, unknown> }>(
  fixtures.cases.map((c: { id: string }) => [c.id, c]),
);
const baselineById = new Map<
  string,
  { id: string; trip: Record<string, { value: unknown; state: string; evidence: string | null }> }
>(baseline.cases.map((c: { id: string }) => [c.id, c]));

// Vietnamese was removed from the product on 2026-09-24 (normalize.ts, questions.ts): there
// is no `vi` reply language and no Vietnamese date convention any more. The corpus still
// carries its ten vi-* messages — these files are the recorded run, they are left as they
// are, and the provenance test at the bottom still reads them — but the cases can no longer
// be replayed *as Vietnamese*. A vi-* message has no Han character in it, so it now detects
// as English, and a yearless pair like vi-09's "05/12" reads month-first for English: the
// replay would have to assert 2027-05-12 as "the day the guest actually wrote", which is a
// date that guest never meant. So every loop below runs over the 20 non-Vietnamese cases.
//
// Coverage this drops, recorded here so it is a known gap rather than a silent one:
//   * language: the recorded run's `language` is no longer compared for the vi-* cases (it
//     still is for every en/zh case, which is the assertion that matters);
//   * vi-09 and vi-10, the two `resolver-language` pairs, no longer exercise the detected
//     language settling a yearless pair — dates.test.ts and extract.test.ts pin that for zh;
//   * vi-04's `diveFrom` was the only dive window the recorded run stated, so no window is
//     kept by this replay any more — robustness.test.ts pins the same phrase-resolution rule;
//   * vi-09's `guests: 8` count is no longer replayed here — robustness.test.ts replays it.
const VI_CASE = /^vi-/;
const replayable = (dataset as Array<{ id: string; text: string }>).filter((item) => !VI_CASE.test(item.id));


// The cases whose check-in the pre-fix pipeline deleted, marked by the generator rather than
// re-listed here. Two tags, and the difference between them is the whole story of the date
// work:
//
//   `:resolver`           the phrase table reads the quote itself, so the model's own date is
//                          never consulted. 17 of the 19.
//   `:resolver-language`  the same, for the two pairs with no year on them that used to be
//                          handed to the model: "05/12" (vi-09) and "12/10" (vi-10) are two
//                          valid calendar dates whichever way they are read, so the table
//                          refused them and corroboration had to judge the model's date. The
//                          guest's language — detected from that same message, the detection
//                          that fills trip.language — leaves exactly one reading now (dates.ts
//                          numericPairReadings). Both messages are Vietnamese, so both were
//                          day/month; with the vi language gone they are no longer replayed
//                          (see VI_CASE above), and zh is what pins the day-first reading now.
//
// `:model` is gone, and it is asserted gone rather than deleted, because it was the tag for the
// cases where the model's own date decided a money field — a model that read the pair
// backwards priced the wrong month. A tag with no cases behind it is the fix.
const recovered = fixtures.cases.filter((c: { provenance: string }) => c.provenance !== "recorded");
// The same list, minus the six Vietnamese cases the replay no longer runs: vi-04/05/06/07 are
// `:resolver` and vi-09/vi-10 are the `:resolver-language` pairs.
const recoveredReplayable = recovered.filter((c: { id: string }) => !VI_CASE.test(c.id));
const idsWithTag = (tag: string) =>
  recovered.filter((c: { provenance: string }) => c.provenance.endsWith(":" + tag)).map((c: { id: string }) => c.id);
const modelDecided = idsWithTag("model");
const languageRead = idsWithTag("resolver-language");

/**
 * The date the guest's own words put the stay on — written from dataset.mock-30.json's
 * text, never from the fixture, so a wrong answer cannot be justified by the file it is
 * compared against. `addDays` counts from RECORDED_TODAY, a Friday (weekday phrases count
 * from there); `monthDay` is the guest's own day and month, with the year implied by "the
 * next time that day comes"; `noDate` is a message that genuinely has no date on it.
 *
 * The vi-* entries are here because the completeness check at the bottom requires an entry
 * for every dataset message, but they are inert: those cases are not replayed (VI_CASE
 * above), so nothing reads them. Their values stay as the Vietnamese reading they were
 * written with, which is what the corpus message meant — it is simply no longer a date this
 * pipeline has any way to arrive at.
 *
 * Two entries disagree with the recorded run on purpose, because the run was wrong:
 * zh-08 (下周五 said on a Friday, which the old resolver pushed out to 2026-10-02) and
 * vi-07 (thứ Bảy tới, which it could not read at all).
 */
const GUEST_DATE: Record<
  string,
  { kind: "addDays"; value: number } | { kind: "monthDay"; value: string } | { kind: "noDate" }
> = {
  "en-01-complete": { kind: "addDays", value: 8 }, // next Saturday
  "en-02-missing-most": { kind: "addDays", value: 1 }, // this weekend
  "en-03-trap-unrelated-number": { kind: "addDays", value: 1 }, // arriving tomorrow
  "en-04-agent-multiple-rooms": { kind: "addDays", value: 7 }, // this Friday
  "en-05-relative-date-idiom": { kind: "addDays", value: 5 }, // in 5 days
  "en-06-padi-open-water": { kind: "monthDay", value: "10-10" }, // starting Oct 10th
  "en-07-fun-diving-package": { kind: "monthDay", value: "11-02" }, // starting Nov 2
  "en-08-family-non-divers": { kind: "monthDay", value: "12-01" }, // coming Dec 1st
  "en-09-trap-price-inquiry": { kind: "monthDay", value: "10-18" }, // 2 nights on Oct 18
  "en-10-solo-diver": { kind: "addDays", value: 7 }, // this Friday
  "vi-01-complete": { kind: "addDays", value: 1 }, // thứ Bảy này
  "vi-02-missing-dates": { kind: "noDate" }, // chưa chốt ngày, khoảng cuối tháng này
  "vi-03-trap-price-number": { kind: "addDays", value: 8 }, // cuối tuần sau
  "vi-04-khoa-hoc-lan-ow": { kind: "monthDay", value: "10-15" }, // từ ngày 15/10
  "vi-05-dai-ly-dat-doan": { kind: "monthDay", value: "11-20" }, // từ ngày 20/11
  "vi-06-gia-dinh-nghi-duong": { kind: "addDays", value: 7 }, // từ thứ Sáu tuần sau
  "vi-07-cuoi-tuan-lan-bien": { kind: "addDays", value: 1 }, // check in thứ Bảy tới
  "vi-08-hoi-gia-chung": { kind: "addDays", value: 1 }, // cuối tuần này
  "vi-09-bay-so-dien-thoai": { kind: "monthDay", value: "12-05" }, // từ ngày 05/12
  "vi-10-thue-xe-rieng": { kind: "monthDay", value: "10-12" }, // từ 12/10
  "zh-01-complete": { kind: "addDays", value: 8 }, // 下周六
  "zh-02-missing-most": { kind: "noDate" }, // 只问价格
  "zh-03-trap-phone-wechat": { kind: "monthDay", value: "10-12" }, // 10月12日
  "zh-04-padi-ow-course": { kind: "monthDay", value: "11-05" }, // 11月5号
  "zh-05-fun-dive-club": { kind: "monthDay", value: "10-20" }, // 10月20日
  "zh-06-agency-booking": { kind: "monthDay", value: "11-15" }, // 11月15日
  "zh-07-family-trip": { kind: "monthDay", value: "12-10" }, // 12月10日
  "zh-08-relative-date": { kind: "addDays", value: 7 }, // 下周五, said on a Friday
  "zh-09-room-only": { kind: "monthDay", value: "10-24" }, // 10月24日
  "zh-10-trap-price-inquiry": { kind: "monthDay", value: "11-08" }, // 11月8日
};

// The one case where the recorded model said nothing about the date at all (the log
// scores it required 0/3), so its fixture has no evidence to reuse when a test injects a
// correct date. "on Oct 18" is quoted from the guest's own message.
const DATE_EVIDENCE: Record<string, string> = { "en-09-trap-price-inquiry": "on Oct 18" };

function addDays(iso: string, days: number): string {
  const d = new Date(`${iso}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

/** The ISO the guest's own phrase means, per GUEST_DATE. */
function guestIso(id: string): string | null {
  const expected = GUEST_DATE[id];
  if (!expected || expected.kind === "noDate") return null;
  return expected.kind === "addDays"
    ? addDays(RECORDED_TODAY, expected.value)
    : `${RECORDED_TODAY.slice(0, 4)}-${expected.value}`;
}

type Field = { value: unknown; state: string; evidence: string | null };
type Trip = Record<string, Field>;
type Model = Record<string, Field>;

function providerReturning(raw: unknown): ExtractProvider {
  return {
    id: "replay:stub",
    call: vi.fn().mockResolvedValue({ raw, tokensIn: 0, tokensOut: 0, cacheReadTokens: 0, ms: 1 }),
  };
}

/**
 * Every replayed dataset message through extract() with its recorded answer — optionally
 * rewritten by `edit`, which is how the three model behaviours below are produced. `calls`
 * counts provider invocations: more than one per case means a retry, i.e. that a fixture
 * answer failed schema validation and the model would have been asked again.
 *
 * The vi-* cases are not replayed at all (see VI_CASE above); the dataset's own file-level
 * checks still read all 30.
 */
async function replay(edit: (id: string, model: Model) => void = () => {}) {
  const trips = new Map<string, Trip>();
  const questions = new Map<string, string[]>();
  let calls = 0;
  for (const item of replayable) {
    const fixture = fixtureById.get(item.id)!;
    const model = structuredClone(fixture.model) as Model;
    edit(item.id, model);
    const provider = providerReturning(model);
    try {
      const outcome = await extract(item.text, provider);
      trips.set(item.id, outcome.trip as unknown as Trip);
      questions.set(item.id, outcome.questions.map((q) => String(q.field)));
    } catch (err) {
      throw new Error(`${item.id}: the recorded answer no longer extracts — ${(err as Error).message}`);
    }
    calls += vi.mocked(provider.call).mock.calls.length;
  }
  return { trips, questions, calls };
}

/** Injects the date the guest actually wrote, as a model that read the message properly. */
function withCorrectDates(id: string, model: Model): void {
  const expected = GUEST_DATE[id];
  if (!expected || expected.kind === "noDate") return;
  const evidence = model.checkIn?.evidence ?? DATE_EVIDENCE[id];
  if (!evidence) throw new Error(`${id} has a date in the guest's words but no evidence phrase to quote`);
  model.checkIn = { value: guestIso(id), state: "stated", evidence };
}

/** The same date, a week late — the error a model makes when it mis-reads a week or a month. */
function withWeekLateDates(id: string, model: Model): void {
  withCorrectDates(id, model);
  if (typeof model.checkIn?.value === "string") model.checkIn = { ...model.checkIn, value: addDays(model.checkIn.value, 7) };
}

/** A model date with nothing in the guest's words to hold it to, which must be refused. */
function withSpeculativeDate(id: string, model: Model): void {
  // zh-02 asks only for a price — no day, no month, no weekday in the message at all, so a
  // model that offers the 30th has nothing in the guest's own words behind it.
  if (id !== "zh-02-missing-most") return;
  model.checkIn = { value: "2026-09-30", state: "stated", evidence: "请问潜水套餐多少钱一位？" };
}

const DIVE_FIELDS = ["diver", "diveFrom", "diveTo"];

describe("eval replay — the recorded deepseek-flash run, re-run offline", () => {
  it("replays all 20 non-Vietnamese cases through the pipeline, with no provider and no retry", async () => {
    const { trips, calls } = await replay();
    expect(trips.size).toBe(replayable.length);
    // One call per case: every recorded answer still passes schema validation, so none of
    // them would have cost the model a second round-trip.
    expect(calls).toBe(replayable.length);
    for (const item of replayable) {
      const trip = trips.get(item.id)!;
      for (const key of Object.keys(baselineById.get(item.id)!.trip)) {
        expect(trip[key], `${item.id}.${key} came back with no state at all`).toBeDefined();
      }
    }
  });

  it("reproduces that run field for field, apart from the check-in dates this work recovers", async () => {
    const { trips } = await replay();
    // Fields where the fixture and the recording are *meant* to differ. The dive rules
    // tightened after that run (below), and the two fields below those belong to code: the
    // recording has the model answering `transportType` itself — quoting the guest's words
    // as its "evidence", the one thing the model is not trusted with — and the fixture
    // deliberately leaves it out so postProcess settles it from `transport` instead. For a
    // declined transfer that is still a value (`none`); for a wanted one it is now `missing`,
    // so this field differs in state and value, not only in the invented evidence. The
    // assertion below pins which of the two shapes each case must have.
    // `guests` is here for the same kind of reason: the recording has vi-09's `guests: 8`
    // for a message that says both 8 and 4, and corroborateCount (counts.ts) turns a count
    // the guest's own words contradict into a question instead of a price. The fixture
    // still carries the model's 8 — the answer is replayed wrong on purpose — so this is
    // the field where the current pipeline is meant to differ from that run. (That case is
    // Vietnamese and is not replayed any more; robustness.test.ts replays the same answer.)
    const intended = new Set([...DIVE_FIELDS, "checkIn", "checkOut", "transportType", "guests"]);
    const changedDates: string[] = [];

    for (const item of replayable) {
      const before = baselineById.get(item.id)!.trip;
      const after = trips.get(item.id)!;

      // The nine fields this work does not touch must be exactly what that run produced.
      for (const [field, previous] of Object.entries(before)) {
        if (intended.has(field)) continue;
        expect(after[field], `${item.id}.${field} changed since that run`).toEqual(previous);
      }

      // transportType is never guessed from the transport answer any more. Only the case the
      // guest has settled is filled in: a declined transfer becomes `none` in postProcess,
      // because "no transfer" needs no further question. A guest who *wants* one without
      // saying one-way or return stays `missing` on purpose, so the question fires and their
      // own answer is what the estimate is priced from. en-06's recording had the model's own
      // `oneway` for a message that only says "need van from NAIA airport" — a guess, not a
      // quote, and one the guest would have been priced for. No fixture states a transfer type
      // of its own, so those two shapes are the only ones this replay can produce.
      if (after.transport.value === true) {
        expect(after.transportType, `${item.id}.transportType must not be guessed from a wanted transfer`).toEqual({
          value: null,
          state: "missing",
          evidence: null,
        });
      } else {
        expect(after.transportType, `${item.id}.transportType of a declined transfer`).toEqual({
          value: "none",
          state: "derived",
          evidence: null,
        });
      }

      // A date that run had already resolved must resolve to the same day — this is the
      // guard on the phrase table: adding entries must not move a date that was right.
      if (before.checkIn.state === "stated") {
        expect(after.checkIn, `${item.id}.checkIn was already right and moved`).toEqual(before.checkIn);
      }

      // A date it deleted is either back (and marked as such in the fixture) or still
      // missing because no model ever offered one (en-09: the run returned nothing at all
      // for that message, which is a model problem, not a date-parsing one).
      if (before.checkIn.state === "missing" && after.checkIn.state === "stated") {
        changedDates.push(item.id);
        expect(
          recoveredReplayable.map((c: { id: string }) => c.id),
          `${item.id} gained a date on its own — the fixture never proposed one`,
        ).toContain(item.id);
      }

      // check-out is arithmetic on the guest's own answers, never the model's date.
      if (after.checkIn.state === "stated" && typeof after.nights.value === "number") {
        expect(after.checkOut.value).toBe(addDays(after.checkIn.value as string, after.nights.value as number));
      } else {
        expect(after.checkOut.state, `${item.id}.checkOut outlived its check-in`).toBe("missing");
      }
      expect(after.checkOut.state === "derived" || after.checkOut.state === "missing").toBe(true);
    }

    expect(changedDates.sort()).toEqual(recoveredReplayable.map((c: { id: string }) => c.id).sort());
  });

  it("keeps a dive window only as a date inside the stay, and asks about every other one", async () => {
    const { trips } = await replay();
    const windowsKept: string[] = [];

    for (const item of replayable) {
      const before = baselineById.get(item.id)!.trip;
      const after = trips.get(item.id)!;
      const stayFrom = after.checkIn.state === "stated" ? (after.checkIn.value as string) : null;
      const stayTo = after.checkOut.state === "derived" ? (after.checkOut.value as string) : null;

      for (const field of DIVE_FIELDS) {
        // ADR-006 Decision 4: dive revenue is priced from `diver` and the window, so
        // anything the run inferred — and anything code cannot settle as a date the stay
        // contains — has to be a question. `diver` is the field that gates the other two.
        if (after[field].state !== "stated") {
          expect(after[field].state, `${item.id}.${field} is a money field and must be asked about`).toBe("missing");
          expect(before[field].state, `${item.id}.${field} was missing in that run too`).not.toBe("stated");
          continue;
        }
        if (field === "diver") {
          expect(after[field], `${item.id}.diver`).toEqual(before[field]);
          continue;
        }
        windowsKept.push(`${item.id}.${field}`);
        expect(after[field].value, `${item.id}.${field} is stated as something that is not a date`).toMatch(
          /^\d{4}-\d{2}-\d{2}$/,
        );
        if (stayFrom) expect((after[field].value as string) >= stayFrom, `${item.id}.${field} starts before the stay`).toBe(true);
        if (stayTo) expect((after[field].value as string) <= stayTo, `${item.id}.${field} ends after the stay`).toBe(true);
      }
    }

    // The one window the recorded run stated was vi-04's `diveFrom: "15/10"` — the guest's own
    // phrase handed back where a date belongs, which code resolves (dates.ts) rather than asking
    // for a date the guest had already written. vi-04 is a Vietnamese case and is no longer
    // replayed, so no recorded window survives here; robustness.test.ts pins the same resolution
    // rule ("resolves the guest's own phrase the way it resolves a check-in").
    expect(windowsKept).toEqual([]);
  });

  it("never keeps a required field with a value the guest did not give — it asks instead", async () => {
    const { trips, questions } = await replay();
    const keptWrong: string[] = [];
    const asked: string[] = [];
    let stated = 0;

    for (const item of replayable) {
      const trip = trips.get(item.id)!;
      const askedHere = questions.get(item.id) ?? [];
      for (const field of REQUIRED_FIELDS) {
        if (item.expected[field]?.state !== "stated") continue;
        stated += 1;
        const actual = trip[field];
        if (actual.state === "stated") {
          // Stated means the guest gave it. A value that is not the one the dataset's own
          // text contains is the money bug this work is about: it is priced as an answer.
          if (item.expected[field].value !== undefined && actual.value !== item.expected[field].value) {
            keptWrong.push(`${item.id}.${field}=${String(actual.value)}`);
          }
          continue;
        }
        // Not stated: the guest's answer is not in the trip, so it has to be asked for.
        asked.push(`${item.id}.${field}`);
        expect(askedHere, `${item.id}.${field} is neither kept nor asked about`).toContain(field);
      }
    }

    // The invariant, and the acceptance check for this work: of the required fields the
    // corpus says the guest stated, none is kept with a value the guest did not give.
    // vi-09's `guests: 8` used to be exactly that — priced, and never asked about — but that
    // case is Vietnamese and is not replayed here (robustness.test.ts replays it).
    expect(stated).toBe(60);
    expect(keptWrong).toEqual([]);
    // Four of the counted fields are not kept, and each is a question rather than a silence
    // (asserted above): en-09's whole message scored 0/3 in that run's own log, and en-10 says
    // "Solo diver" without the model recording a count. Pinned so a new gap shows up as a
    // failure here rather than as a field that quietly stopped being asked about.
    expect(asked).toEqual([
      "en-09-trap-price-inquiry.checkIn",
      "en-09-trap-price-inquiry.guests",
      "en-09-trap-price-inquiry.nights",
      "en-10-solo-diver.guests",
    ]);
  });

  it("recovers every deleted date as the day the guest actually wrote", async () => {
    const { trips } = await replay();
    // The 19 the corpus marked recovered, minus the six Vietnamese cases not replayed.
    expect(recoveredReplayable).toHaveLength(13);

    for (const [id, trip] of trips) {
      const expected = GUEST_DATE[id];
      expect(expected, `${id} has no entry in GUEST_DATE`).toBeDefined();
      if (trip.checkIn.state !== "stated") {
        expect(trip.checkIn.value, `${id} kept a value while not being stated`).toBeNull();
        continue;
      }
      expect(expected.kind, `${id} ended up with a date, but the message has none`).not.toBe("noDate");
      if (expected.kind === "monthDay") {
        expect(String(trip.checkIn.value)).toMatch(new RegExp(`-${expected.value}$`));
      } else {
        expect(trip.checkIn.value).toBe(addDays(RECORDED_TODAY, expected.value));
      }
      expect(trip.checkIn.evidence, `${id} has a date but no quote from the guest`).not.toBeNull();
    }
  });

  it("scores the same as that run's own report, plus the 19 fields it lost", async () => {
    const { trips } = await replay();

    const aggregate = (tripOf: (id: string) => Trip) => {
      let fabricated = 0;
      let requiredTotal = 0;
      let requiredCorrect = 0;
      let stated = 0;
      let evidenceOk = 0;
      for (const item of replayable) {
        const trip = tripOf(item.id);
        const scored = scoreCase(item, trip);
        fabricated += scored.fabricated;
        requiredTotal += scored.requiredTotal;
        requiredCorrect += scored.requiredCorrect;
        const ev = checkEvidence(trip, item.text);
        stated += ev.stated;
        evidenceOk += ev.evidenceOk;
      }
      return { fabricated, requiredTotal, requiredCorrect, stated, evidenceOk };
    };

    const before = aggregate((id) => baselineById.get(id)!.trip);
    const after = aggregate((id) => trips.get(id)!);

    // The recording's own report, re-derived from the baseline file by the live runner's
    // scoring code over the non-Vietnamese cases (results-deepseek.log reports "Required
    // fields correct: 63/87" for all 30; the vi-* cases are not part of this replay).
    expect(before.requiredTotal).toBe(60);
    expect(before.requiredCorrect).toBe(43);

    expect(after.fabricated, "a field was invented for a message that never stated it").toBe(0);
    expect(after.evidenceOk).toBe(after.stated); // verbatim, checked in code, 100%
    expect(after.stated).toBeGreaterThan(before.stated);

    // Exactly the recovered date fields, and nothing else, changed hands. The live run's ≥95%
    // threshold is not reachable with *these* answers — en-09's three missing fields are the
    // model's errors, preserved in the fixture on purpose. (vi-09's `guests: 8` was the other
    // preserved error; it is Vietnamese and not replayed here.)
    expect(after.requiredTotal).toBe(before.requiredTotal);
    expect(after.requiredCorrect).toBe(before.requiredCorrect + recoveredReplayable.length);
  });
});

describe("eval replay — what the pipeline does with the date a model offers", () => {
  it("keeps every date the guest wrote, and asks only about the messages that have none", async () => {
    const { trips, questions } = await replay(withCorrectDates);

    for (const [id, trip] of trips) {
      const expected = GUEST_DATE[id];
      if (expected.kind === "noDate") {
        expect(trip.checkIn.state, `${id} has no date in it and must still be asked about`).toBe("missing");
        expect(questions.get(id)).toContain("checkIn");
        continue;
      }
      expect(trip.checkIn.state, `${id} states a date and must not be re-asked for it`).toBe("stated");
      expect(trip.checkIn.value).toBe(guestIso(id));
      expect(trip.checkIn.evidence).not.toBeNull();
      expect(questions.get(id), `${id} has its date, so it must not be asked again`).not.toContain("checkIn");
    }
  });

  it("refuses a week-late date, and never records one as stated", async () => {
    const { trips } = await replay(withWeekLateDates);

    for (const [id, trip] of trips) {
      if (trip.checkIn.state !== "stated") continue;
      // Whatever the model said, a stated date is the guest's own day: either the
      // resolver read the phrase itself, or corroboration checked it against the words.
      expect(trip.checkIn.value, `${id} recorded a date the guest did not write`).toBe(guestIso(id));
    }

    // Nothing is left to the model any more. The two cases that were — the ambiguous day/month
    // pairs "05/12" (vi-09) and "12/10" (vi-10) — are Vietnamese and are excluded from this
    // replay (see VI_CASE). dates.test.ts and extract.test.ts pin the same mechanism for zh,
    // where the detected language settles a yearless pair before the model's date is consulted.
    expect(modelDecided).toEqual([]);
    expect(languageRead.filter((id) => !VI_CASE.test(id))).toEqual([]);
  });

  it("refuses a date the guest's own words do not support", async () => {
    const { trips, questions } = await replay(withSpeculativeDate);
    const trip = trips.get("zh-02-missing-most")!;
    // zh-02 asks only what a dive package costs: no day, no month and no weekday anywhere in
    // it. A model offering the 30th is guessing, and a guessed check-in is a wrong price
    // (dates.ts, corroborateDatePhrase).
    expect(trip.checkIn.state).toBe("missing");
    expect(trip.checkIn.value).toBeNull();
    expect(trip.checkIn.evidence).toBeNull();
    expect(questions.get("zh-02-missing-most")).toContain("checkIn");
  });
});

describe("eval replay — the priced fields the score used to ignore", () => {
  it("scores transport the way the live runner does, and pins the recorded mistake", async () => {
    const { trips } = await replay();
    const mismatched: string[] = [];
    let checked = 0;

    for (const item of replayable) {
      const priced = checkPricedFields(item, trips.get(item.id)!);
      checked += priced.checked;
      for (const m of priced.mismatches) mismatched.push(`${item.id}.${m.field}`);
    }

    // Some of the messages say something about the airport transfer, one way or the other.
    expect(checked).toBe(14);

    // The recorded answers make this mistake — a guest who says they are driving themselves
    // comes back as `transport: true`, with their own sentence ("自己开车过去") as the
    // evidence, so evidence enforcement could not see it and nothing scored it. It was made
    // twice in the recording, the other time in Vietnamese (vi-07); that case is no longer
    // replayed (see VI_CASE). The answers are replayed wrong on purpose (make-fixtures.mjs);
    // what the assertion buys is that the mistake is *visible* in the score, and that a second
    // one cannot appear without failing here.
    expect(mismatched).toEqual(["zh-09-room-only.transport"]);
  });
});

describe("eval fixtures", () => {
  it("say where they came from, and which cases were restored by hand", async () => {
    expect(fixtures.provenance.recordedToday).toBe(RECORDED_TODAY);
    expect(baseline.provenance.recordedToday).toBe(RECORDED_TODAY);
    expect(fixtures.provenance.recording).toBe(baseline.provenance.recording);
    expect(fixtures.provenance.provider).toContain("deepseek");
    expect(fixtures.provenance.generatedBy).toBe("eval/make-fixtures.mjs");

    const ids = (list: Array<{ id: string }>) => new Set(list.map((c) => c.id));
    expect(ids(fixtures.cases)).toEqual(ids(dataset));
    expect(ids(baseline.cases)).toEqual(ids(dataset));

    // The 19 the pre-fix pipeline deleted, marked by provenance so the suite can tell a
    // recovered date from one that was there all along.
    const authored = fixtures.cases.filter((c: { provenance: string }) => c.provenance !== "recorded");
    expect(authored).toHaveLength(19);
    for (const c of authored) expect(c.provenance.startsWith("authored-checkIn:")).toBe(true);
    // Two of those 19 are the `resolver-language` pairs (vi-09, vi-10), which are Vietnamese
    // and so are not replayed any more; the tag survives in the files as provenance. No
    // check-in is decided by the model's own date any more.
    expect(modelDecided).toEqual([]);
    expect(languageRead).toHaveLength(2);

    // GUEST_DATE is this file's only independent expectation about dates: a message added
    // to the dataset without one would otherwise be scored as "no opinion" and pass.
    for (const item of dataset as Array<{ id: string }>) {
      expect(GUEST_DATE[item.id], `${item.id} is missing from GUEST_DATE`).toBeDefined();
    }
  });
});



